add conf check action before reload group conf, and update output log format.

diff --git a/cfiojobs b/cfiojobs
--- a/cfiojobs
+++ b/cfiojobs
@@ -13,7 +13,7 @@
 # last edit :   20181225
 ###########################################################
 
-script_version=0.12.73
+script_version=0.12.74
 
 ssh_timeout=15
 process_reservation=128
@@ -34,11 +34,12 @@ concurrent_pipe_fd=$host_concurrency_max
 while ls -l /proc/self/fd/ |grep -q " $concurrent_pipe_fd " ;do 
     concurrent_pipe_fd=$[host_concurrency_max + 1]
 done 
-#date=$(date "+%Y-%m-%d_%H:%M:%S")
+date_time=$(date "+%Y-%m-%d_%H:%M:%S")
 date="$(date +%Y%m%d%H%M)"
 g_conf="$0"".grp"
 b_conf="$0"".blk"
 j_conf="$0"".job"
+#[[ -f /etc/init.d/functions ]] && . /etc/init.d/functions 
 
 function _clean_up(){
     # clean up tmp files
@@ -85,7 +86,23 @@ function _test_abort(){
     echo "test stoped at $(date)" >>$output_dir/recover.log
     [[ $send_fio == "True" ]] && echo "test \"$output_dir\" stoped now" || echo "tasks all stoped" 
 }
-trap "echo -e '\n job reload group config with signal 1'; _host_group_check" 1
+function _reload_host_group_config(){
+    _segline "reload host group config file with signal 1"
+    if _grp_conf_check ;then 
+        _host_group_check
+        local reload_stat=$?
+        if [[ $reload_stat -eq 0 ]] ;then
+            _info "reload host group config file seccess"
+        else
+            _error "reload host group config file failed."
+        fi 
+        _segline "host group config file reloaded"
+    else
+        _warn "The current host group config file can not be reloaded by $0 !!"
+        _warn "The old grp conf info will be remained, but please check your new host group config file as soon as possible!!"
+    fi 
+}
+trap " _reload_host_group_config " 1
 trap "echo -e '\n job stoped with user signals, stop running, please wait ...'; _test_abort; exit $check_stat" 2 3 15
 
 ##############################################################################################
@@ -153,6 +170,7 @@ usage :
             options: 
             -t             check host group config file format.
             -g groups      run commands on certain host groups in $g_conf (sep with comma)
+                           (note that all the host group info will be reloaded when signal 1 is recived.)
             -a             run commands on all host group set
             -x hosts       make an exception on these hosts (sep with comma)
             -X groups      make an exception on these host groups (sep with comma)
@@ -456,6 +474,7 @@ function _unquiet(){
     else 
         # echo 
         echo -e "$@"
+        return 0
     fi
 }
 function _tmp_quiet(){
@@ -707,6 +726,7 @@ fi
 }
 #----------------------------------------|failure info |-----------------------
 function _record_fail(){
+    _check_output_dir 
     if [[ $send_fio == "True" ]] || [[ -n $harvest_file_group_list  ]] ;then
         local failure_time=$(date "+%Y-%m-%d %H:%M:%S")
         local failure_type="${FUNCNAME[1]}" # parent function name 
@@ -730,6 +750,15 @@ function _devfail(){
     # give device check failed info 
     _red "  host:$host_ip dev:$dev_name not a valid test device."
     _record_fail
+}
+function _info(){
+    echo "[$(_blue "INFO")] [ $date_time ]: $@"
+}
+function _warn(){
+    echo "[$(_yellow "WARN")] [ $date_time ]: $@"
+}
+function _error(){
+    echo "[$(_red "ERROR")] [ $date_time ]: $@"
 }
 
 ##############################################################################################
@@ -837,7 +866,14 @@ function _grp_conf_check(){
         done  << EOF
 $(_format_conf $g_conf)
 EOF
-        [[ $check_stat -ne 1 ]] && echo "host group config file checked ok." || exit 1
+        if [[ $check_stat -ne 1 ]] ;then
+            _info "host group config file check ok."
+            return 0
+        else
+            _erro "host group config file check error."
+            return 1
+            #exit 1
+        fi 
     else
         echo "host list file not fond."
     fi
@@ -885,7 +921,7 @@ function _group_check(){
                             # reformat hostname.
                             HOST_GROUP_IP_LIST_ARRAY[$host_group_name]=$(_uniq_list $(_format_conf $host_conf ) | sed 's/-/_/g' )
                         else
-                            echo "Warning: host group config file: $g_conf, group name: \"$host_group_name\" , ip list file: \"$host_conf\" is missing "
+                            _warn "host group config file: $g_conf, group name: \"$host_group_name\" , ip list file: \"$host_conf\" is missing "
                         fi
                     else
                           HOST_GROUP_IP_LIST_ARRAY[$host_group_name]=$(_uniq_list ${group_info[5]//,/ })
@@ -895,7 +931,7 @@ function _group_check(){
                 # if group info lost, skip or exit
                 # 3. check from last, find last missing info index, and print its name.
                     for index in {1..5} ;do
-                       [[ -z ${group_info[$index]} ]] && echo "Warning: host group config file: $g_conf, group name: \"$host_group_name\" , ${index_name_array[$index]} info missing!"
+                       [[ -z ${group_info[$index]} ]] && _warn "host group config file: $g_conf, group name: \"$host_group_name\" , ${index_name_array[$index]} info missing!"
                     done
                     grp_stat=1
                     # remove from host_group_list
@@ -979,7 +1015,7 @@ function _job_group_check(){
                 # check missing array element. check from the last, which element is missing.
                 # if index2 is missing index3 will be take as index2, so always find the last missing index, index 1-5
                 for index in {1..5} ;do
-                   [[ -z ${job_group_info[$index]} ]] && echo "Warning: job group config file: $j_conf, $job_group_name: ${index_name_array[$index]} info missing!"
+                   [[ -z ${job_group_info[$index]} ]] && _warn "job group config file: $j_conf, $job_group_name: ${index_name_array[$index]} info missing!"
                 done
                 _error_interrupt
             else
@@ -1049,7 +1085,7 @@ function _blk_group_check(){
                     blk_stat="1"
                     blk_group_list=${blk_group_list/$blk_group_name/}
                     # give info which is missing.
-                    echo "blk group: $blk_group_name, device list info is missing!"
+                    _error "blk group: $blk_group_name, device list info is missing!"
                     # if test with the rest group
                     _error_interrupt
                 else
@@ -1064,7 +1100,7 @@ function _blk_group_check(){
             # 1.2 name missing in conf
             else
             #remove the invalid group which its name not exist in conf
-                echo "Warning: blk config file: $b_conf, $blk_group_name: device list info is missing!"
+                _warn "blk config file: $b_conf, $blk_group_name: device list info is missing!"
                 blk_stat="1"
                 blk_group_list=${blk_group_list/$blk_group_name/}
                 # skip missing test with the rest group
@@ -1396,7 +1432,7 @@ function _parse_host_info(){
             #echo $job_group_name 
         fi
         if [[ -z ${host_user// /} ]] || [[ -z ${host_port// /} ]] || [[ -z ${ip_list// /} ]] ;then
-            echo "${FUNCNAME[@]}: group: \"$1\", ssh login info is missing."
+            _error "${FUNCNAME[@]}: group: \"$1\", ssh login info is missing."
             continue || exit 1
         fi
         #remove x_host list from group ip_list
@@ -1427,7 +1463,7 @@ function _ping_check(){
 function _ssh_send(){
 #send command info to host when ssh_user, ssh_ip, ssh_port was set
     if [[ $# -lt 1 ]] ;then
-        echo "${FUNCNAME[@]} warning: no command info to send!" 
+        _warn "${FUNCNAME[@]} : no command info to send!" 
         return 1
     else
         #if expect -v &>/dev/null ;then 
@@ -2519,7 +2555,7 @@ function _check_output_dir(){
         local default_output_dir=$(_get_default_output_dir)
         if [[ -z $output_dir ]] ;then
             output_dir="$default_output_dir"
-            _yellow "INFO: no output dir name specified, \"$output_dir\" will be the default name."
+            _info "no output dir name specified, \"$output_dir\" will be the default name."
         #2nd check: hold files.
         elif [[ -d $output_dir ]] || mkdir -p $output_dir ;then
             :
@@ -2527,10 +2563,10 @@ function _check_output_dir(){
             # either 1 or 2 failed.
             if [[ $output_dir == $default_output_dir ]] ;then
                 # dir creation failure for default name.
-                _red "Warn: the output dir creation failed !" 
+                _warn "the output dir creation failed !" 
             else
                 # creation failure for specified name.
-                _yellow "INFO: now use \"$output_dir\" as the new output directory, is this ok?"
+                _info "now use \"$output_dir\" as the new output directory, is this ok?"
             fi
             _timeout "15"
         fi
@@ -3108,7 +3144,7 @@ done
 #running options check
     _show_info
     if [[ $conf_check == "True" ]] ;then 
-        _grp_conf_check
+        _grp_conf_check || exit 1
         _blk_conf_check
         _job_conf_check
     fi
